# Generated by Django 4.1.1 on 2022-10-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', models.BooleanField()),
                ('alternate_mode', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
